/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;



import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void rollTest() {
        // Arrange
        Library sut = new Library();
        int[] testArray;

        // Act
        testArray = sut.roll(3);

        // Assert
        assertEquals(3, testArray.length);
        assertTrue(testArray[0] >= 1 && testArray[0] <= 6);
    }

    @Test void duplicateTest() {
        // Arrange
        Library sut = new Library();
        int[] array = {2, 8, 8, 3};

        // Act & Assert
        assertTrue(sut.containsDuplicates(array), "This array has duplicates");

    }

    @Test void testCalculateArrayAverage() {
        // Arrange
        Library sut = new Library();
        int[] array = {2, 8, 8, 3};
        int expected = 5;

        // Act
        int actual = sut.calculateAverage(array);

        // Assert
        assertEquals(expected, actual);
    }

    @Test
    void testLowestAverageArray() {
        // Arrange
        Library sut = new Library();
        int[][] array = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] expected = {55, 54, 60, 53, 59, 57, 61};

        // Act
        int[] actual = sut.lowestAverageArray(array);

        // Assert
        assertArrayEquals(expected, actual);
    }
}
