/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;



import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void rollTest() {
        // Arrange
        Library sut = new Library();
        int[] testArray;

        // Act
        testArray = sut.roll(3);

        // Assert
        assertEquals(3, testArray.length);
        assertTrue(testArray[0] >= 1 && testArray[0] <= 6);
    }

    @Test void duplicateTest() {
        // Arrange
        Library sut = new Library();
        int[] array = {2, 8, 8, 3};

        // Act & Assert
        assertTrue(sut.containsDuplicates(array), "This array has duplicates");

    }

    @Test void testCalculateArrayAverage() {
        // Arrange
        Library sut = new Library();
        int[] array = {2, 8, 8, 3};
        int expected = 5;

        // Act
        int actual = sut.calculateAverage(array);

        // Assert
        assertEquals(expected, actual);
    }
}
